name: CI

on:
  push:
    branches:
      - dev/endMovementM

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
 
      - name: Restore dependencies
        run: dotnet restore SpaceBattle.Tests

      - name: Install Required Tools
        run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-coverage
          dotnet tool install coverlet.console

      - name: Build
        run: dotnet build SpaceBattle.Lib --no-restore /p:ContinuousIntegrationBuild=true

      - name: Checkstyle
        run: dotnet format --verify-no-changes

      - name: Test
        run: cd SpaceBattle.Tests/ &&  dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

      - name: Coverage and Tests
        run: dotnet coverlet SpaceBattle.Tests/bin/Debug/net8.0/SpaceBattle.Tests.dll --target "dotnet" --targetargs "test --no-build" -f=opencover -o="coverage.xml"
 