name: CI

on:
  push:
    branches:
      - 'Lab**'

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
 
      - name: Restore dependencies
        run: dotnet restore SpaceBattle.Tests

      - name: Build
        run: dotnet build SpaceBattle.Lib --no-restore /p:ContinuousIntegrationBuild=true

      - name: Test
        run: cd SpaceBattle.Tests/ &&  dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

      - name: Coverage
        run: cd SpaceBattle.Tests/ &&  dotnet test --configuration $(buildConfiguration) --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/ /p:Exclude="[MyAppName.DebugHost]*%2c[MyAppNamet.WebHost]*%2c[MyAppName.App]*"

      - name: Checkstyle
        run: dotnet format --verify-no-changes
 